const characters = {
	ql_weinasi: {
		sex: "female",
		group: "hua",
		hp: 3,
		skills: ["ql_yongtan", "ql_daolie", "ql_tongxing"],
		img: "extension/五花米线/skin/ql_weinasi.jpg",
		dieAudios: [],
	},
    ql_tianwang: {
		sex: "male",
		group: "hua",
		hp: 5,
		career: "suwei",
		skills: ["ql_shenhu", "ql_zhensui"],
		img: "extension/五花米线/skin/ql_tianwang.jpg",
		dieAudios: [],
	},
	ql_laotou: {
		sex: "male",
		group: "hua",
		hp: 4,
		career: "qingrui",
		skills: ["ql_yinjian", "ql_xiaoyao", "ql_huihao"],
		img: "extension/五花米线/skin/ql_laotou.jpg",
		dieAudios: [],
	},
	ql_luxian: {
		sex: "male",
		group: "meng",
		hp: 3,
		skills: ["ql_shengqiang", "ql_toushe", "ql_xili"],
		img: "extension/五花米线/skin/ql_luxian.jpg",
		dieAudios: ["ext:五花米线/audio/die/ql_luxian.mp3"],
	},
	ql_tienan: {
		sex: "male",
		group: "meng",
		hp: 4,
		skills: ["ql_mingchui", "ql_buhuai", "ql_tianjixian"],
		img: "extension/五花米线/skin/ql_tienan.jpg",
		dieAudios: ["ext:五花米线/audio/die/ql_tienan.mp3"],
	},
	ql_matijin: {
		sex: "male",
		group: "hua",
		hp: 3,
		skills: ["ql_shuoyao", "ql_jincheng", "ql_linrui"],
		img: "extension/五花米线/skin/ql_matijin.jpg",
		dieAudios: ["ext:五花米线/audio/die/ql_matijin.mp3"],
	},
	ql_linzhijin: {
		sex: "male",
		group: "hua",
		hp: 1,
		skills: [],
		isUnseen: true,
		img: "extension/五花米线/skin/ql_linzhijin.jpg",
		dieAudios: ["ext:五花米线/audio/die/ql_linzhijin.mp3"],
	},
	ql_liujin: {
		sex: "male",
		group: "hua",
		hp: 5,
		career: "suwei",
		skills: ["ql_zhujia", "ql_chuanshuo"],
		img: "extension/五花米线/skin/ql_liujin.jpg",
		dieAudios: ["ext:五花米线/audio/die/ql_liujin.mp3"],
	},
	ql_danao: {
		sex: "female",
		group: "hua",
		hp: 3,
		career: "yuanji",
		skills: ["ql_zhigu", "ql_leimi"],
		img: "extension/五花米线/skin/ql_danao.jpg",
		dieAudios: ["ext:五花米线/audio/die/ql_danao.mp3"],
	},
	ql_caifeng: {
		sex: "male",
		group: "hua",
		hp: 3,
		maxHp: 3,
		hujia: 3,
		career: "yuanji",
		skills: ["ql_luoxia", "ql_wanlai"],
		img: "extension/五花米线/skin/ql_caifeng.jpg",
		dieAudios: ["ext:五花米线/audio/die/ql_caifeng.mp3"],
	},
	ql_thua: {
		sex: "female",
		group: "hua",
		hp: 3,
		career: "goushu",
		skills: ["ql_yinhun", "ql_furang", "ql_wange"],
		img: "extension/五花米线/skin/ql_thua.jpg",
		dieAudios: ["ext:五花米线/audio/die/ql_thua.mp3"],
	},
	ql_jinwu: {
		sex: "none",
		group: "hua",
		hp: 3,
		career: "goushu",
		skills: ["ql_jiuyao", "ql_luoyan"],
		isUnseen: true,
		img: "extension/五花米线/skin/ql_jinwu.jpg",
	},
	ql_linggui: {
		sex: "none",
		group: "hua",
		hp: 6,
		career: "suwei",
		skills: ["ql_xianzhi"],
		isUnseen: true,
		img: "extension/五花米线/skin/ql_linggui.jpg",
	},
    ql_liuzhang: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["ql_dimou","ql_juni","ql_shouchuan"],
		img: "extension/五花米线/skin/ql_liuzhang.jpg",
		dieAudios: ["ext:五花米线/audio/die/ql_liuzhang.mp3"],
	},
    ql_jiangwan: {
		sex: "male",
		group: "shu",
		hp: 3,
		//career: "qingrui",
		skills: ["ql_shengxi","ql_zhifa","ql_jianshen"],
		img: "extension/五花米线/skin/ql_jiangwan.jpg",
		dieAudios: ["ext:五花米线/audio/die/ql_jiangwan.mp3"],
	},
	ql_niuzun: {
		sex: "female",
		group: "hua",
		hp: 4,
		career: "qingrui",
		skills: ["ql_yinge", "ql_wanling", "ql_leishang","qlweiye"],
		img: "extension/五花米线/skin/ql_niuzun.jpg",
		dieAudios: ["ext:五花米线/audio/die/ql_niuzun.mp3"],
	},
	ql_guoping: {
		sex: "female",
		group: "hua",
		hp: 3,
		career: "zhanlue",
		skills: ["ql_shengduan", "ql_wuwei"],
		img: "extension/五花米线/skin/ql_guoping.jpg",
		dieAudios: ["ext:五花米线/audio/die/ql_guoping.mp3"],
	},
	ql_xiaoma: {
		sex: "male",
		group: "hua",
		hp: 5,
		maxHp: 5,
		hujia: 0,
		career: "suwei",
		skills: ["ql_xingkong", "ql_qiji", "ql_tafeng"],
		img: "extension/五花米线/skin/ql_xiaoma.jpg",
		dieAudios: ["ext:五花米线/audio/die/ql_xiaoma.mp3"],
	},
	ql_yaya: {
		sex: "female",
		group: "hua",
		hp: 3,
		career: "zhanlue",
		skills: ["ql_silv", "ql_fulu", "ql_futao"],
		img: "extension/五花米线/skin/ql_yaya.jpg",
		dieAudios: ["ext:五花米线/audio/die/ql_yaya.mp3"],
	},
	ql_baishi: {
		sex: "female",
		group: "hua",
		hp: 3,
		career: "goushu",
		skills: ["ql_sanqu", "ql_pailian", "ql_shengyue"],
		img: "extension/五花米线/skin/ql_baishi.jpg",
		dieAudios: ["ext:五花米线/audio/die/ql_baishi.mp3"],
	},
	hb_hui: {
		sex: "male",
		group: "meng",
		hp: 3,
		skills: ["hb_luokuan", "hb_zaie", "hb_jingan", "hb_moran", "hb_fenxin"],
		img: "extension/五花米线/skin/hb_hui.jpg",
		dieAudios: ["ext:五花米线/audio/die/hb_hui.mp3"],
	},
	ql_tuma: {
		sex: "female",
		group: "hua",
		hp: 4,
		career: "qingrui",
		skills: ["ql_yixing", "ql_tongyao"],
		img: "extension/五花米线/skin/ql_tuma.jpg",
		dieAudios: ["ext:五花米线/audio/die/ql_tuma.mp3"],
	},
	ql_caomao: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["ql_hongfa", "ql_fulong", "ql_dengzhu"],
		img: "extension/五花米线/skin/ql_caomao.jpg",
		dieAudios: ["ext:五花米线/audio/die/ql_caomao.mp3"],
	},
	ql_kuisangti: {
		sex: "male",
		group: "meng",
		hp: 4,
		skills: ["ql_xuemeng", "ql_tuofu", "ql_aoang"],
		img: "extension/五花米线/skin/ql_kuisangti.jpg",
		dieAudios: ["ext:五花米线/audio/die/ql_kuisangti.mp3"],
	},
	ql_efeiliusi: {
		sex: "male",
		group: "meng",
		hp: 3,
		skills: ["ql_yening"],
		img: "extension/五花米线/skin/ql_efeiliusi.jpg",
		dieAudios: ["ext:五花米线/audio/die/ql_efeiliusi.mp3"],
	},
	ql_weilusi: {
		sex: "male",
		group: "meng",
		hp: 3,
		skills: ["ql_chouyu", "ql_kuwei", "ql_baisuo"],
		img: "extension/五花米线/skin/ql_weilusi.jpg",
		dieAudios: ["ext:五花米线/audio/die/ql_weilusi.mp3"],
	},
	ql_xuchu: {
		sex: "male",
		group: "wei",
		hp: 5,
		maxHp: 10,
		skills: ["ql_zhanshen", "ql_douwu"],
		img: "extension/五花米线/skin/ql_xuchu.jpg",
		dieAudios: ["ext:五花米线/audio/die/ql_xuchu.mp3"],
	},
	ql_zhaoxin: {
		sex: "male",
		group: "meng",
		hp: 4,
		skills: ["ql_guojue", "ql_xunci", "ql_xinwei"],
		img: "extension/五花米线/skin/ql_zhaoxin.jpg",
		dieAudios: ["ext:五花米线/audio/die/ql_zhaoxin.mp3"],
	},
	ql_yaheng: {
		sex: "male",
		group: "meng",
		hp: 4,
		skills: ["ql_hengzhi", "ql_chie", "ql_dashe"],
		img: "extension/五花米线/skin/ql_yaheng.jpg",
		dieAudios: ["ext:五花米线/audio/die/ql_yaheng.mp3"],
	},
	ql_xushao: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["ql_pingjian"],
		img: "extension/五花米线/skin/ql_xushao.jpg",
		dieAudios: ["ext:五花米线/audio/die/ql_xushao.mp3"],
	},
	ql_jianmo: {
		sex: "male",
		group: "meng",
		hp: 3,
		skills: ["ql_cisi", "ql_anren", "ql_damie"],
		img: "extension/五花米线/skin/ql_jianmo.jpg",
		dieAudios: ["ext:五花米线/audio/die/ql_jianmo.mp3"],
	},
	ql_wuxianpipa: {
		sex: "female",
		group: "hua",
		hp: 3,
		career: "goushu",
		skills: ["ql_pipa", "ql_raoliang", "ql_zhuanzhou", "ql_fangrui"],
		img: "extension/五花米线/skin/ql_wuxianpipa.jpg",
		dieAudios: ["ext:五花米线/audio/die/ql_wuxianpipa.mp3"],
	},
	ql_taozi: {
		sex: "female",
		group: "hua",
		hp: 3,
		career: "goushu",
		skills: ["ql_chuntao", "ql_wangxiang"],
		img: "extension/五花米线/skin/ql_taozi.jpg",
		dieAudios: ["ext:五花米线/audio/die/ql_taozi.mp3"],
	},
	ql_laoshi: {
		sex: "female",
		group: "hua",
		hp: 2,
		maxHp: 3,
		hujia: 3,
		career: "zhanlue",
		skills: ["ql_chuandao", "ql_qilie", "ql_shibiao"],
		img: "extension/五花米线/skin/ql_laoshi.jpg",
		dieAudios: ["ext:五花米线/audio/die/ql_laoshi.mp3"],
	},
	ql_caoang: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["ql_zuiyuan", "ql_chengyi"],
		img: "extension/五花米线/skin/ql_caoang.jpg",
		dieAudios: ["ext:五花米线/audio/die/ql_caoang.mp3"],
	},
	ql_shierhua: {
		sex: "female",
		group: "hua",
		hp: 3,
		career: "zhanlue",
		skills: ["ql_jishi", "ql_yueling", "ql_xiangmeng"],
		img: "extension/五花米线/skin/ql_shierhua.jpg",
		dieAudios: ["ext:五花米线/audio/die/ql_shierhua.mp3"],
	},
	ql_niaozun: {
		sex: "female",
		group: "hua",
		hp: 3,
		career: "zhanlue",
		skills: ["ql_xunji", "ql_kanpo", "ql_jiean"],
		img: "extension/五花米线/skin/ql_niaozun.jpg",
		dieAudios: ["ext:五花米线/audio/die/ql_niaozun.mp3"],
	},
	ql_zhanghe: {
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 5,
		skills: ["ql_duanyuan", "ql_fanzhan", "ql_qibian"],
		img: "extension/五花米线/skin/ql_zhanghe.jpg",
		dieAudios: ["ext:五花米线/audio/die/ql_zhanghe.mp3"],
	},
	ql_laola: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["ql_bihu", "ql_xuanji", "ql_canheng", "ql_baopo"],
		img: "extension/五花米线/skin/ql_laola.jpg",
		dieAudios: ["ext:五花米线/audio/die/ql_laola.mp3"],
	},
	ql_lingtong: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["ql_fenlu", "ql_jiechou", "ql_yinqi"],
		img: "extension/五花米线/skin/ql_lingtong.jpg",
		dieAudios: ["ext:五花米线/audio/die/ql_lingtong.mp3"],
	},
	ql_xiahoushang: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["qlposhan", "qltanyong"],
		img: "extension/五花米线/skin/ql_xiahoushang.jpg",
		dieAudios: ["ext:五花米线/audio/die/ql_xiahoushang.mp3"],
		names: "夏侯|尚",
	},
	ql_sunjian: {
		sex: "male",
		group: "wu",
		hp: 6,
		skills: ["qlfendeng", "qlyinghun", "qlxiongyong"],
		img: "extension/五花米线/skin/ql_sunjian.jpg",
		dieAudios: ["ext:五花米线/audio/die/ql_sunjian.mp3"],
		isZhu: true,
	},
	ql_qingongbo: {
		sex: "female",
		group: "hua",
		hp: 3,
		career: "goushu",
		skills: ["qlqinsheng", "qllingyong"],
		img: "extension/五花米线/skin/ql_qingongbo.jpg",
		dieAudios: ["ext:五花米线/audio/die/ql_qingongbo.mp3"],
	},
	tr_xihe: {
		sex: "female",
		group: "shen",
		hp: Infinity,
		skills: ["qlmuhui", "qltianguo", "qlqicai", "qlchanghong", "startGame_tr_xihe"], //
		img: "extension/五花米线/skin/tr_xihe.GIF",
		dieAudios: ["ext:五花米线/audio/die/tr_xihe.mp3"],
		//isBoss: true,
		//isUnseen: true,
	},
	qlhuangzhong: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["qlfengjian", "qlguanshi"],
		img: "extension/五花米线/skin/qlhuangzhong.jpg",
		dieAudios: ["ext:五花米线/audio/die/huangzhong.mp3"],
	},
	chuqi: {
		sex: "female",
		group: "shen",
		hp: 4,
		maxHp: 7,
		hujia: 0,
		skills: ["zhusui"],
		img: "extension/五花米线/skin/chuqi.jpg",
		dieAudios: ["ext:初七/audio/die/chuqi.mp3"],
	},
	qljushou: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["qlshipan", "qlkangfu"],
		img: "extension/五花米线/skin/qljushou.jpg",
		dieAudios: ["ext:五花米线/audio/die/qljushou.mp3"],
	},
	ql_bianzhong: {
		sex: "female",
		group: "hua",
		hp: 5,
		career: "suwei",
		skills: ["qlsanyin", "qljili"],
		img: "extension/五花米线/skin/ql_bianzhong.jpg",
		dieAudios: ["ext:五花米线/audio/die/ql_bianzhong.mp3"],
	},
	qlqianli: {
		sex: "male",
		group: "hua",
		hp: 3,
		career: "goushu",
		skills: ["qldubu", "qlchongluan"],
		img: "extension/五花米线/skin/qlqianli.jpg",
		dieAudios: ["ext:五花米线/audio/die/qlqianli.mp3"],
	},
	qllukang: {
		sex: "male",
		group: "wu",
		hp: 5,
		skills: ["qlzhuwei", "qlkeshou", "qljuejie"],
		img: "extension/五花米线/skin/qllukang.jpg",
		dieAudios: ["ext:五花米线/audio/die/qllukang.mp3"],
	},
	ql_sushadanyi: {
		sex: "female",
		group: "hua",
		hp: 3,
		career: "goushu",
		skills: ["qlpingwen", "qlchousi", "qlbojian"],
		img: "extension/五花米线/skin/ql_sushadanyi.jpg",
		dieAudios: ["ext:五花米线/audio/die/ql_sushadanyi.mp3"],
	},
	qiulitwo: {
		sex: "male",
		group: "hua",
		hp: 4,
		maxHp: 6,
		hujia: 0,
		skills: ["qllvling", "qlmouding"],
		img: "extension/五花米线/skin/qiulitwo.jpg",
		dieAudios: ["ext:五花米线/audio/die/qiulitwo.mp3"],
	},
	ql_shuijingbei: {
		sex: "female",
		group: "hua",
		hp: 4,
		maxHp: 5,
		career: "qingrui",
		skills: ["qltitou", "qltuosha"],
		img: "extension/五花米线/skin/ql_shuijingbei.jpg",
		dieAudios: ["ext:五花米线/audio/die/ql_shuijingbei.mp3"],
	},
	ql_touying: {
		sex: "female",
		group: "hua",
		hp: 4,
		career: "qingrui",
		skills: ["qlyingjie"],
		isUnseen: true,
		img: "extension/五花米线/skin/ql_touying.jpg",
		dieAudios: ["ext:五花米线/audio/die/ql_touying.mp3"],
	},
	qlgujian: {
		sex: "female",
		group: "hua",
		hp: 8,
		maxHp: 8,
		hujia: 0,
		career: "qingrui",
		skills: ["qlhanshan", "qlcangfeng", "qllingling", "qlduyou", "qlmanxue"],
		img: "extension/五花米线/skin/qlgujian.jpg",
		dieAudios: ["ext:五花米线/audio/die/qlgujian.mp3"],
		isUnseen: true,
	},
	qlxuejing: {
		sex: "female",
		group: "hua",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		career: "qingrui",
		skills: ["qlhanshan", "qlcangfeng", "qllingling"],
		img: "extension/五花米线/skin/qlxuejing.jpg",
		dieAudios: ["ext:五花米线/audio/die/qlxuejing.mp3"],
	},
	qlliyan: {
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qlhuaizhi"],
		img: "extension/五花米线/skin/qlliyan.jpg",
		dieAudios: ["ext:五花米线/audio/die/qlliyan.mp3"],
	},
	qlwangjun: {
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qlyinlian", "qlpozhou"],
		img: "extension/五花米线/skin/qlwangjun.jpg",
		dieAudios: ["ext:五花米线/audio/die/qlwangjun.mp3"],
	},
	qlxinxianying: {
		sex: "female",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["qlcaishi", "qldongwei", "qlzhongjian", "qlquanan"],
		img: "extension/五花米线/skin/qlxinxianying.jpg",
		dieAudios: ["ext:五花米线/audio/die/qlxinxianying.mp3"],
	},
	qlzerong: {
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qlyinian", "qlfozong"],
		img: "extension/五花米线/skin/qlzerong.jpg",
		dieAudios: ["ext:五花米线/audio/die/qlzerong.mp3"],
		isUnseen: true,
	},
	qlchedanbei: {
		sex: "male",
		group: "hua",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		career: "qingrui",
		skills: ["qlbuqi", "qlfangdao"],
		img: "extension/五花米线/skin/qlchedanbei.jpg",
		dieAudios: ["ext:五花米线/audio/die/qlchedanbei.mp3"],
	},
	qlshichangshi: {
		sex: "male",
		group: "qun",
		hp: 1,
		maxHp: 1,
		hujia: 0,
		skills: ["qldanggu", "qlmowang"],
		img: "extension/五花米线/skin/qlshichangshi.jpg",
		dieAudios: ["ext:五花米线/audio/die/qlshichangshi.mp3"],
	},
	qlzoushi: {
		sex: "female",
		group: "wu",
		hp: 3,
		maxHp: 3,
		skills: ["qlhuoxin", "qlmiluan"],
		img: "extension/五花米线/skin/qlzoushi.jpg",
		dieAudios: ["ext:五花米线/audio/die/qlzoushi.mp3"],
	},
	qldaqiao: {
		sex: "female",
		group: "shen",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qlleguose", "qlliuli"],
		img: "extension/五花米线/skin/qldaqiao.jpg",
		dieAudios: ["ext:五花米线/audio/die/qldaqiao.mp3"],
	},
	qlcaiwenji: {
		sex: "female",
		group: "shen",
		hp: 7,
		maxHp: 7,
		hujia: 0,
		skills: ["qlqingleng", "qlaige", "qlduanqu"],
		img: "extension/五花米线/skin/qlcaiwenji.GIF",
		dieAudios: ["ext:五花米线/audio/die/qlcaiwenji.mp3"],
	},
	qljiangwei: {
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qltiaoxin", "qlchengzhi"],
		img: "extension/五花米线/skin/qljiangwei.jpg",
		dieAudios: ["ext:五花米线/audio/die/qljiangwei.mp3"],
	},
	qiuli: {
		sex: "male",
		group: "hua",
		hp: Infinity,
		maxHp: Infinity,
		hujia: Infinity,
		skills: ["ql_whmx"],
		img: "extension/五花米线/skin/qiuli.jpg",
		dieAudios: ["ext:五花米线/audio/die/qiuli.mp3"],
	},
	ql_wuxing: {
		sex: "male",
		group: "hua",
		hp: 3,
		career: "zhanlue",
		skills: ["qlwuxing", "qllianzhu", "qlfentian"],
		img: "extension/五花米线/skin/ql_wuxing.jpg",
		dieAudios: ["ext:五花米线/audio/die/ql_wuxing.mp3"],
	},
	qlyanghu: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["qlrongchu"],
		img: "extension/五花米线/skin/qlyanghu.jpg",
		dieAudios: ["ext:五花米线/audio/die/qlyanghu.mp3"],
		isUnseen: true,
	},
	yh_luxun: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["yhjunlve", "yhcuike"],
		img: "extension/五花米线/skin/yh_luxun.jpg",
		dieAudios: ["ext:五花米线/audio/die/yhluxun.mp3"],
	},
	qlsunquan: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["qlquanxue", "qlquanheng", "qlchengxiong"],
		zhu: true,
		img: "extension/五花米线/skin/qlsunquan.jpg",
		dieAudios: ["ext:五花米线/audio/die/qlsunquan.mp3"],
	},
	qlhuoguomiji: {
		sex: "female",
		group: "hua",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		career: "qingrui",
		skills: ["qllianzhu2", "xinfu_tushe", "qlyunwei"],
		img: "extension/五花米线/skin/qlhuoguomiji.jpg",
		dieAudios: ["ext:五花米线/audio/die/qlhuoguomiji.mp3"],
	},
	ql_ying_jihuoyishou: {
		sex: "none",
		group: "hua",
		hp: 20,
		maxHp: 20,
		hujia: 0,
		career: "suwei",
		skills: ["ql_ying_huoyu", "ql_ying_xundi", "ql_ying_huoshi", "ql_ying_xiezhu"],
		img: "extension/五花米线/skin/ql_ying_jihuoyishou.jpg",
		dieAudios: ["ext:五花米线/audio/die/ql_ying_jihuoyishou.mp3"],
	},
	yh_ganning: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["yhpoxi", "yhjieying"],
		img: "extension/五花米线/skin/yh_ganning.jpg",
		dieAudios: ["ext:五花米线/audio/die/yhganning.mp3"],
	},
	yh_xuyou: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["yhchenglve", "yhshicai", "yhcunmu"],
		img: "extension/五花米线/skin/yh_xuyou.jpg",
		dieAudios: ["ext:五花米线/audio/die/yhxuyou.mp3"],
	},
	qlzhaoyun: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["qllongwei", "qlzhandi"],
		img: "extension/五花米线/skin/qlzhaoyun.jpg",
		dieAudios: ["ext:五花米线/audio/die/qlzhaoyun.mp3"],
	},
	qlyucongwang: {
		sex: "male",
		group: "hua",
		hp: 3,
		career: "goushu",
		skills: ["qlyulian", "qltianfa"],
		img: "extension/五花米线/skin/qlyucongwang.jpg",
		dieAudios: ["ext:五花米线/audio/die/qlyucongwang.mp3"],
	},
	qlfuronglu: {
		sex: "female",
		group: "hua",
		hp: 3,
		career: "goushu",
		skills: ["qlhusheng", "qlyingguang", "qlyingyuan"],
		img: "extension/五花米线/skin/qlfuronglu.jpg",
		dieAudios: ["ext:五花米线/audio/die/qlfuronglu.mp3"],
	},
	qlweisuojiaju: {
		sex: "female",
		group: "hua",
		hp: 5,
		career: "suwei",
		skills: ["qlzhuomu", "qlgongming"],
		img: "extension/五花米线/skin/qlweisuojiaju.jpg",
		dieAudios: ["ext:五花米线/audio/die/qlweisuojiaju.mp3"],
	},
	qlmoxingta: {
		sex: "male",
		group: "hua",
		hp: 5,
		career: "suwei",
		skills: ["qlnixing"],
		img: "extension/五花米线/skin/qlmoxingta.jpg",
		dieAudios: ["ext:五花米线/audio/die/qlmoxingta.mp3"],
		isUnseen: true,
		isAiForbidden: true,
	},
	qlxizhicai: {
		sex: "male",
		group: "shen",
		hp: 1,
		maxHp: 1,
		hujia: 0,
		skills: ["qlfaxiang", "qlxianfu"],
		img: "extension/五花米线/skin/qlxizhicai.GIF",
		dieAudios: ["ext:五花米线/audio/die/qlxizhicai.mp3"],
	},
	qlxiahoulingnv: {
		sex: "female",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["qlguimian", "qljihuo", "qlgujie"],
		img: "extension/五花米线/skin/qlxiahoulingnv.jpg",
		dieAudios: ["ext:五花米线/audio/die/qlxiahoulingnv.mp3"],
	},
	qlzhaoxiang: {
		sex: "female",
		group: "shu",
		hp: 1,
		maxHp: 5,
		hujia: 0,
		skills: ["qlmeiying", "qlfuhan"],
		img: "extension/五花米线/skin/qlzhaoxiang.jpg",
		dieAudios: ["ext:五花米线/audio/die/qlzhaoxiang.mp3"],
	},
	qlzhuling: {
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qlzhanyi"],
		img: "extension/五花米线/skin/qlzhuling.jpg",
		dieAudios: ["ext:五花米线/audio/die/qlzhuling.mp3"],
	},
	qltaishici: {
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qlwuwei", "qljuezhan"],
		img: "extension/五花米线/skin/qltaishici.jpg",
		dieAudios: ["ext:五花米线/audio/die/qltaishici.mp3"],
	},
	qlzuoci: {
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["change"],
		img: "extension/五花米线/skin/qlzuoci.jpg",
		dieAudios: ["ext:五花米线/audio/die/qlzuoci.mp3"],
	},
	qlwangyun: {
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["qldingxi", "qlweichao", "qlhuoxin"],
		img: "extension/五花米线/skin/qlwangyun.jpg",
		dieAudios: ["ext:五花米线/audio/die/qlwangyun.mp3"],
		isUnseen: true,
	},
	qlshenpei: {
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qlspweiye", "qlspyongzhi"],
		img: "extension/五花米线/skin/qlshenpei.jpg",
		dieAudios: ["ext:五花米线/audio/die/qlshenpei.mp3"],
	},
	qlsunyi: {
		sex: "male",
		group: "wu",
		hp: 5,
		maxHp: 5,
		hujia: 0,
		skills: ["qlxuezao", "qlxiaozhen", "qlnusu"],
		img: "extension/五花米线/skin/qlsunyi.jpg",
		dieAudios: ["ext:五花米线/audio/die/qlsunyi.mp3"],
	},
	/*qlcaiwenji: {
		sex: "female",
		group: "shen",
		hp: 7,
		skills: ["qlaige", "qlduanqu"],
		img: "extension/五花米线/skin/qlcaiwenji.jpg",
		dieAudios: ["ext:五花米线/audio/die/qlcaiwenji.mp3"],
	},*/
	qlgoujian: {
		sex: "female",
		group: "hua",
		hp: 4,
		career: "qingrui",
		skills: ["qlwoxin", "qlchengxu", "qlyuejia"],
		img: "extension/五花米线/skin/qlgoujian.jpg",
		dieAudios: ["ext:五花米线/audio/die/qlgoujian.mp3"],
	},
	qlgoujian2: {
		sex: "female",
		group: "hua",
		hp: 4,
		career: "qingrui",
		skills: ["qlwoxin", "qlchengxu"],
		img: "extension/五花米线/skin/qlgoujian.jpg",
		dieAudios: ["ext:五花米线/audio/die/qlgoujian.mp3"],
		isUnseen: true,
	},
	qldashenkan: {
		sex: "male",
		group: "hua",
		hp: 3,
		career: "yuanji",
		skills: ["qlhuajin", "qlfucui"],
		img: "extension/五花米线/skin/qldashenkan.jpg",
		dieAudios: ["ext:五花米线/audio/die/qldashenkan.mp3"],
	},
	qlyexingtongpai: {
		sex: "male",
		group: "hua",
		hp: 4,
		career: "qingrui",
		skills: ["qljichi", "qljisha"],
		img: "extension/五花米线/skin/qlyexingtongpai.jpg",
		dieAudios: ["ext:五花米线/audio/die/qlyexingtongpai.mp3"],
	},
	ql_puyuan: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["ql_jiangxin", "ql_pozhu", "ql_qiaoyi"],
		img: "extension/五花米线/skin/ql_puyuan.jpg",
		dieAudios: ["ext:五花米线/audio/die/ql_puyuan.mp3"],
	},
	ql_changxingongdeng: {
		sex: "female",
		group: "hua",
		hp: 3,
		career: "goushu",
		skills: ["ql_ranji", "ql_quan", "ql_yuhui", "ql_huiguang"],
		img: "extension/五花米线/skin/ql_changxingongdeng.jpg",
		dieAudios: ["ext:五花米线/audio/die/ql_changxingongdeng.mp3"],
	},
	qlkaier: {
		sex: "female",
		group: "shen",
		hp: Infinity,
		skills: ["qlsacreSanction"],
		img: "extension/五花米线/skin/qlkaier.jpg",
		dieAudios: ["ext:五花米线/audio/die/qlkaier.mp3"],
		isUnseen: true,
	},
	qlligui: {
		sex: "male",
		group: "hua",
		hp: 3,
		career: "zhanlue",
		skills: ["qlyuanfang", "qlbaoshang"],
		img: "extension/五花米线/skin/qlligui.jpg",
		dieAudios: ["ext:五花米线/audio/die/qlligui.mp3"],
	},
	qlsilongsifengzuo: {
		sex: "male",
		group: "hua",
		hp: 5,
		career: "qingrui",
		skills: ["ql_longyin", "ql_fengming", "ql_lijie"],
		img: "extension/五花米线/skin/qlsilongsifengzuo.jpg",
		dieAudios: ["ext:五花米线/audio/die/qlsilongsifengzuo.mp3"],
	},
};
export default characters;
