const characters = {
    ql_chiyuan: {
        sex: "female",
        group: "ql_door",
        hp: 4,
        skills: ["ql_bingchuan", "ql_binghe"],
    },
    ql_tangtian: {
        sex: "female",
        group: "ql_door",
        hp: 4,
        skills: ["ql_shenxing", "ql_yijin", "ql_guanci"],
    },
    ql_jinnian: {
        sex: "female",
        group: "ql_door",
        hp: 3,
        maxHp: 3,
        skills: ["ql_chuanshu", "ql_dansuan"],
    },
    ql_lingyong: {
        sex: "male",
        group: "ql_door",
        hp: 4,
        maxHp: 4,
        skills: ["ql_qunqi", "ql_diance"],
    },
    ql_jiangwutong: {
        sex: "female",
        group: "ql_door",
        hp: 4,
        maxHp: 4,
        //hujia: 1,
        skills: ["ql_erxiang", "ql_jiahui"],
    },
    ql_qingluo: {
        sex: "female",
        group: "ql_door",
        hp: 4,
        maxHp: 4,
        skills: ["ql_wanbu", "ql_meixin"],
    },
    ql_qiaosimian: {
        sex: "female",
        group: "ql_door",
        hp: 3,
        maxHp: 3,
        skills: ["ql_jishou", "ql_fenhuo"],
    },
    ql_baishuran: {
        sex: "female",
        group: "ql_door",
        hp: 4,
        maxHp: 4,
        skills: ["ql_zhuofan", "ql_shoudu"],
    },
    ql_jiyu: {
        sex: "female",
        group: "ql_door",
        hp: 4,
        maxHp: 4,
        skills: ["ql_qiaojin", "ql_jinpo", "ql_fanci", "ql_youlong", "ql_yanzi"],
    },
    ql_xueshi: {
        sex: "female",
        group: "ql_door",
        hp: 4,
        maxHp: 4,
        skills: ["ql_yingci", "ql_lianci", "ql_shuangci"],
    },
    ql_qingjiuqiu: {
        sex: "female",
        group: "ql_door",
        hp: 4,
        maxHp: 4,
        skills: ["ql_jiuwei", "ql_lingbo", "ql_shepo", "ql_meixin"],
    },
    ql_xueshuang: {
        sex: "female",
        group: "ql_door",
        hp: 4,
        maxHp: 4,
        skills: ["ql_shuangci"],
    },
    ql_xuelian: {
        sex: "female",
        group: "ql_door",
        hp: 4,
        maxHp: 4,
        skills: ["ql_lianci"],
    },
    ql_xueying: {
        sex: "female",
        group: "ql_door",
        hp: 4,
        maxHp: 4,
        skills: ["ql_yingci"],
    },
    ql_linlingning: {
        sex: "female",
        group: "ql_door",
        hp: 1,
        maxHp: 1,
        skills: ["ql_jijie", "ql_luyou"],
    },
    ql_yelingxi: {
        sex: "female",
        group: "ql_door",
        hp: 3,
        maxHp: 4,
        skills: ["ql_youren", "ql_fengling"],
    },
    ql_shenshen: {
        sex: "female",
        group: "ql_door",
        hp: 4,
        skills: ["ql_yingce", "ql_kaiqu"],
    },
    ql_sangya: {
        sex: "female",
        group: "ql_door",
        hp: 4,
        skills: ["ql_pingchou", "ql_fensha", "ql_yaomei"],
        isUnseen: true,
        isAiForbidden: true,
    },
    ql_suyunsong: {
        sex: "male",
        group: "ql_door",
        hp: 3,
        maxHp: 4,
        skills: ["ql_qizhuan"],
    },
    ql_wener: {
        sex: "female",
        group: "ql_door",
        hp: 4,
        skills: ["ql_lintie", "ql_bianzhuang"],
    },
};

export default characters;
